MP_NUM_THREADS=5  THEANO_FLAGS=device=cuda0 flags=-lopenblas python -u 1-shot/main.py \
	-d 200 \
	-i 100 \
	-o 100 \
	-p attention \
	-u 1 \
	-t 5,5,0,0 \
	-c lstm \
	-m attn2hist \
	--stats-file result/stats_gru.json \
	--domain overnight-calendar \
	-k 5 \
	--num-samples 10 \
	--dev-seed 0 \
	--model-seed 0 \
	--train-data data/0-shot \
	--dev-data data/0-shot/calendar_test.tsv \
